### ISSUE TITLE
Coveralls not working

### ISSUE THREAD

**Issue by daberer** [TUW-GEO/flagit#1]
coveralls not working, probably because of a bug in .travis.yml.

**Comment by wpreimes** [comment]
in `.travis.yml` change ` - conda env create -n flagit python=${TRAVIS_PYTHON_VERSION}` to  ` - conda create -n flagit python=${TRAVIS_PYTHON_VERSION}` and see if that helps

**Comment by wpreimes** [comment]
try adding `pytest-cov` to the environment file. althought that should not be necessary it should fix it for now. Also add pip to the environment file and add pytest and pytest-cov as pip packages there instead of conda packages (see our other packages)
