### ISSUE TITLE
Rolling window size array causing runtime error

### ISSUE THREAD

**Issue by mikahpinegar** [TUW-GEO/flagit#3]
I work with a research team and we are hoping to use this package to automate cleaning soil moisture data we collect.

I've forked your repo and when I try to build it it gives me the following error `ValueError: window must be an integer 0 or greater` 

This is coming from lines 339, 340, and 350.
https://github.com/TUW-GEO/flagit/blob/f7201a8c9b6f6a05cbfcfc54df162ac08a2b33fb/src/flagit/flagit.py#L339
https://github.com/TUW-GEO/flagit/blob/f7201a8c9b6f6a05cbfcfc54df162ac08a2b33fb/src/flagit/flagit.py#L340
https://github.com/TUW-GEO/flagit/blob/f7201a8c9b6f6a05cbfcfc54df162ac08a2b33fb/src/flagit/flagit.py#L350

I'm trying to come up with a solution to this that will still calculate the original formula listed in the paper referenced in the readme. If I simply replace the window with 25 it runs fine, but I'm not sure if this is what you were intending. I can't find anything online about passing an array of weights in as a window to the rolling method.

Thanks for the help!

**Comment by daberer** [comment]
Hi @mikahpinegar. many thanks for your interest. Will look into it and check back with you. currently we are working on a new version. Did you try using a python 3.6 environment?

**Comment by daberer** [comment]
as I recall, what I tried to do with this rolling window is take 25 observations but skipping the current observation.

**Comment by mikahpinegar** [comment]
i installed the virtual environment using conda and the instructions listed in the readme. i suppose it's possible i'm still using my other version of python (3.9) and not the virtual env. let me check. also, thanks for the quick response!

**Comment by daberer** [comment]
thank you @mikahpinegar - i will have a look and write you by tomorrow afternoon CET :)

**Comment by mikahpinegar** [comment]
ok after some setup this is resolved by using python 3.6. i'm going to open another issue pertaining to data with different time intervals. thanks for the help!
